/* eslint-disable quotes */

export const poemsData = [
  {
    id: 1,
    title: 'Dil Aakhir Tu Kyu Rota Hai...',
    poem: `Jab Jab Dard Ka Baadal Chhaya\nJab Gham Ka Saya Lehraaya\nJab aansoo Palkon Tak Aaya\nJab Yeh Tanha Dil Ghabraaya\nHum Ne Dil Ko Yeh Samjhaya\nDil Aakhir Tu Kyun Rota Hai\nDuniya Mein Yun Hi Hota Hai\nYeh Jo Gehre Sannate Hain \nWagt Ne Sabko Hi Baante Hain\nThoda Gham Hai Sabka Qissa \nThodi Dhoop Hai Sabka Hissa\nAankh Teri Bekaar Hi Nam Hai\nHar Pal Ek Naya Mausam Hai\nKyun Tu Aise Pal Khota Hai\nDil aakhir Tu Kyun Rota Hai`,
    author: 'Javed Akhtar',
    img: 'https://i.ibb.co/pdjDdv3/javed-akhtar.webp',
    cover: 'https://source.unsplash.com/hBzrr6m6-pc',
  },
  {
    id: 2,
    title: 'Mai Shunya Pe Sawaar Hoon...',
    poem: 'Mai Shunya pe sawaar hoon\nBe adab sa mai khumar hoon\nMushkilo se mai kya darun\nMai khud keher hazaar hoon\nMai Shunya pe sawaar hoon\n\nKi unch neech se pare\nMajal aankh me bhare \nMai lad pada hu raat se \nMashaal haath me liye\nNa surya mere saath hai\nToh kya nayi ye baat hai\nWo sham ko tha dhal gya\nWo raat se tha darr gaya\nMai joognuon ka yaar hoon\nMai shunya pe sawaar hoon!\n\nKi bhawnaayein hai mar chuki\nSamwednaayein ab khatm hai\n   Ki ab dard se kya darun\nZindagi hi zakhm hai\nMai beech rah ki maat hoon\nBejaan-syaah raat hoon\nMai kaali ka shringaar hoon\nMai shunya pe sawar hoon!\n',
    author: 'Zakir Khan',
    img: 'https://i.ibb.co/5xMwbqt/Zakir-khan.webp',
    cover: 'https://source.unsplash.com/1XgFFEG_RGA',
  },
  {
    id: 3,
    title: 'Main Aur Meri Awaargi...',
    poem: 'Phirte hai kabse dar badar\nAb is nagar ab us nagar\nEk duusre ke Ham-safar\nMain aur meri aawaargi\n\nNa aasaan har raah guzar\nNa meherbaan har ek nazar\nJaayein to jaayein kidhar\nMai aur meri aawaargi\n\nHam bhi kabhi aazaad the\nAise kahaan barbaad the\nMasroor the dil shaad the\nWoh chaal esi chal gya\nHam bujh gye dil jal gya\nNikle jalaa k apna Ghabraaya\nMain aur meri aawaargi\n\nYe dil hi tha jo seh gya\nWoh baat esi kar gya\nKehne ko fir kya reh gya\nAshkon ka dariya bhar gya\nJab keh kr wo dilbar gya\nTere liye Main mar gya\nRote hain uske raat bhar\nMain aur meri aawaargi\n\nJab ham dam-o-ham raaz tha\nTab aur hi andaaz tha\nAb soz hai tb saaz tha\nAb sharm hai tb naaz tha\nAb mujhse ho to ho bhi kya\nHai saath wo to wo bhi kya\nEk behunar ek besabar\nMain aur meri aawaargi\n\nAb ghum uthaaein kisliye\nYeh dil jalaaein kisliye\nAansu bahaaein kis liye\nYu jaan gawaaein kis liye\nPesha na ho jiska sifan\nDhundhenge ab aisa sanam\nHonge kabhi to kaargar\nMain aur meri aawaargi\n',
    author: 'Nusrat Fateh Ali Khan',
    img: 'https://i.ibb.co/vkvZr54/nusrat.webp',
    cover: 'https://i.ibb.co/vv0ZmdV/road.webp',
  },
  {
    id: 4,
    title: 'Lord Ram In Court...',
    poem: 'Jo baha tha khoon, uske duur tak chiitein gaye,\nKal adalar me punah, shri ram ghasite gaye\n\nJudge ne bola hey prabhu Hamko shama hai chaahiye\nAap naam jad hue hai Kathghare me aaiye\n\nAllah nadarad hai, the jabki unko bhi summon gaye\nAisa sunka kathghare mein ram ji fir tan gaye\n\nRam bole mai hindu muslim, dono k hi saath hu \nMai hi allah, Main hi nanak, Mai hi ayodhya naath hu\nTretayug mein jisliye maine liya avatar tha\nAaj dekhta hu to lagta hai ki sab bekaar tha.\n\nKevat aur shabri ke bahane bhed-bhav ko toda tha\nTumko shamjhaane ko maine, sita tak ko choda tha\nMere mandir k liye jab, tum the rath pe chad rahe\nDesh k ek kone me the Kashmiri pandit mar rahe\nFir meri hi saugandh kha k kaam esa kar gaye\nMere liye dange hue aur mere hi bache mar gaye\n\nKhair..\nAb bhi samay hai, chhod apni paat do,\nJanmbhumi pe ghar banao,begharon me baat do\nEsa krna hu mai kehta , param-punya ka kary hai\nNyay, ahinsa, parmarth prem, yhi to ram raaj hai.\n\nTab bich me bola kisi ne jab wo tha ukta gaya\nRamchandra ka bhes banake ye kon musalmaan aa gaya.\nEsa kehna hu mai bhaiyya, esa halla mach gaya\nJo ain time pe kat liya, bas wo hi tha jo bach gaya\nFir ram bhakto k hi haathon, ram ji peete gaye\nJo baha tha khoon uske duur tak chite gaye\nJo baha tha khoon uske duur tak chite gaye\n',
    author: 'Gaurav Tripathi',
    img: 'https://i.ibb.co/HGLWSTv/gaurav-tripathi.webp',
    cover: 'https://i.ibb.co/R3sxMj9/lord-ram.webp',
  },
  {
    id: 5,
    title: 'Kathputli...',
    poem: 'Kabhi Kabhi mai dekhta hu or sochta hoon\nKi zindagi hai jaise ek kathputli ka khel \nKi ise chalaata koi aur hai par lagta jaise hum\nKi isme milta bahut zada hai par lagta jaise kum\nKi isme sbki kismet pehle se hi tay hai\nKi isme sbke dukh sabki khusiyon ka raaz samay hai.\n\nPhir Socha sab tay hai to kyu koi ese dukh paata hai\nDin raat ki mehnat se wo kya khota hai…kya paata hai\nPar dhyaan se socha to yeh paaya\nKi sab rachne waale ke ye bhi alag khel hai\nKi jaise aadhe dhaage isne apne aap hi chhor diye hai\nHamko apni raah khud banaane marzi se ye khol diye hai\nSocha hoga ki zra aazaadi inke mann me laake to dekhu\nKaise istamaal krte hai ise zra jaake to dekhu\n\nPar ye aazaadi ka swaad badaa nirala\nKuch ka mann bahut safed, kuch ka kaala\nHui rachayta se ek galti khol diye usne bahut dhaage\nKathputli to ek dusre se lad pde , ab kya kara jaae aage?\n\nFir use ek tarkeeb sujhi, nikaali usne jaadui chadi duuji\nPakdaaye kuch dhaage do ko kum krne kuch paap\nAur un dono ko naam diya “Maa aur Baap”\n\nSikhlaayi ek baat ho ske jisse sabka mel\nBataya usne saara waha ka racha gaya khel\n\nKi hamein chalaata koi ek hi hai, to us naate ham sab to hue bhai\nFir kyu insaan insaan ko hi maar kar ban raha hai kasaayi\nYe Alag Kapde, dharm, sb khule dhaago ki hi to maaya hai\nUsi ne sara moh ka yeh khel alag rachaya hai\n\nAre hataa do in aakho ki patti jiska naam mazhab\nTbi samjh paaoge asli dharm ka matlab\nBand kro ye kattarbaazi, chhor do ladai\nApnaao ek dusre ko aur banjaao sab bhai\n\nTabhi ban paega Kathputli khel ka kuch arth\nAgar jo rahoge ese hi to ho jaega sab nirarth\n',
    author: 'Kuldeep Kaira',
    img: 'https://i.ibb.co/HL8mkX6/kathputli-poet.webp',
    cover: 'https://i.ibb.co/rv8wZFp/kathputli.webp',
  },
  {
    id: 6,
    title: 'Shayari by Waseem barelvi...',
    poem: "apne chehre se jo zāhir hai chhupā.eñ kaise\nterī marzī ke mutābiq nazar aa.eñ kaise \n\n\n\njahāñ rahegā vahīñ raushnī luTā.egā \nkisī charāġh kā apnā makāñ nahīñ hotā \n\n\n\ndukh apnā agar ham ko batānā nahīñ aatā \ntum ko bhī to andāza lagānā nahīñ aatā \n\n\n\nāsmāñ itnī bulandī pe jo itrātā hai \nbhuul jaatā hai zamīñ se hī nazar aatā hai\n\n\n\nvo jhuuT bol rahā thā baḌe salīqe se \nmaiñ e'tibār na kartā to aur kyā kartā \n\n\n\n",
    author: 'Waseem Barelvi',
    img: 'https://i.ibb.co/KxtJZzW/waseem-canvas.webp',
    cover: 'https://i.ibb.co/vwXkQns/waseem-barelvi.webp',
  },
  {
    id: 7,
    title: 'Ghalib in Jail...',
    poem: 'Ghalib hai hawalat me, Premchand ke sath me\nMuh me kapda thusa hua hai, Hathkadiyan hai hath me\n\nShayar Lekhak jab bikne lage, Sab chod kaseede likhne lage\nYe dono yun behuda huye, baki logo se juda hue\nJo andhiyaro me marte the, Roushan unko ye karte the\nPichhdo ko in ne Ram kiya, khud ka apna Islam kiya\nInki itni aukat badhi, hakim ke seedhi lat padi\nTab usne bheja thullo ko, kuch pandit, priest aur mullo ko\nFir inka aisa hal hua, Dam lena bhar bhi muhal hua\nDar janta me Phailaya gaya, Haule haule fuslaya gaya\nUlti Ganga jab bahne lagi, Gaddar inhe hi kahne lagi\n\nTab baith Kothri, kari me, Apni fansi ki taiyari me\nshayar fir bhi wo mara nahi, wo kathakar bhi dara nahi\nNakhun kalam se dikhne lage, wo diwaro par likhne lage\nJeevan Bandhan jab tod gaye, sirf ek sandesha chhod gaye\n\nBolan se tulsi hue, Bolat rahe kabeer\nBolan pe badh pade, Jag ki badhe peer\nkala srijan wo dharm hai, jinse upje ved\nkala srijan ke ki maut par jug jug kare hai khed\n',
    author: 'Gaurav Tripathi',
    img: 'https://i.ibb.co/HGLWSTv/gaurav-tripathi.webp',
    cover: 'https://i.ibb.co/X5JRdcr/ghalib-in-jail.webp',
  },
];
